name: ci_gpg_test
on:
  workflow_dispatch:
#  schedule:
#    - cron:  '30 6 1 * *'

jobs:
  release:
    runs-on: ubuntu-20.04  
    strategy:
      matrix:
        ##### EDIT ME #####  
        EDITION: [xfce]
        BRANCH: [stable]
        SCOPE: [minimal]
        ###################
    steps:
      -
        name: Build ISO
        env:
          EDITION: ${{ matrix.EDITION }}
          BRANCH: ${{ matrix.BRANCH }}
          SCOPE: ${{ matrix.SCOPE }}
          ##### EDIT ME #####
          KERNEL: "linux510"
          CODE_NAME: "Ornara"
          VERSION: "test_upload"
          ###################
        run: |                
          [ "$SCOPE" == "minimal" ] && unset SCOPE
          
          echo "file1" > file1
          echo "file2" > file2
          echo "file3" > file3

                 
          sudo apt-get install paperkey gpg
          
          echo "Unpacking keys; exiting debug mode to redact..."
          set +x
          
          echo "setup values"
          GPG_HOMEDIR="$(mktemp -d -t gnupg.XXX)"
          SECRET_KEY_FILE="$GPG_HOMEDIR/secret.key"
          PUBLIC_KEY_FILE="$GPG_HOMEDIR/public_key.gpg"
          GPG="gpg --homedir=$GPG_HOMEDIR"
          
          ls $GPG_HOMEDIR
          
          # unpack public key
          echo "$CI_PUB_KEY" | base64 --decode > "$PUBLIC_KEY_FILE"

          # unpack secret key
          echo "$CI_GPG_SECRET" | base64 --decode > "$SECRET_KEY_FILE"
          
          paperkey --pubring "$PUBLIC_KEY_FILE" --secrets "$SECRET_KEY_FILE" \
          | $GPG --import --passphrase $CI_GPG_PASSPHRASE
          
          ls $GPG_HOMEDIR

          echo "Secrets unpacked..."
          set -x
          
          echo "some cmd"
          $GPG --detach-sign --use-agent -u "${CI_GPG_KEY}" file1
          
          echo "cleaning up"
          shred "$GPG_HOMEDIR"
          rm -rvf "$GPG_HOMEDIR"
          echo "script done"
