name: ci_gpg_test
on:
  workflow_dispatch:
#  schedule:
#    - cron:  '30 6 1 * *'

jobs:
  release:
    runs-on: ubuntu-20.04  
    strategy:
      matrix:
        ##### EDIT ME #####  
        EDITION: [xfce]
        BRANCH: [stable]
        SCOPE: [minimal]
        ###################
    steps:
      -
        name: Build ISO
        env:
          EDITION: ${{ matrix.EDITION }}
          BRANCH: ${{ matrix.BRANCH }}
          SCOPE: ${{ matrix.SCOPE }}
          ##### EDIT ME #####
          KERNEL: "linux510"
          CODE_NAME: "Ornara"
          VERSION: "test_upload"
          ###################
        run: |                
          [ "$SCOPE" == "minimal" ] && unset SCOPE
          
          echo "file1" > file1.gpg
          echo "file2" > file2
          echo "file3" > file3

          echo "FILE_PATH=file1" >> $GITHUB_ENV
          echo "FILE_SHA256=file2" >> $GITHUB_ENV
          echo "FILE_PKG=file3" >> $GITHUB_ENV
          echo "VERSION=test_upload" >> $GITHUB_ENV
          
          sudo apt-get install paperkey gpg
          
          echo "setup values"
          GPG_HOMEDIR="$(mktemp -d -t gnupg.XXX)"
          SECRET_KEY_FILE="$GPG_HOMEDIR/secret.key"
          PUBLIC_KEY_FILE="$GPG_HOMEDIR/public_key.gpg"
          GPG="gpg --homedir=$GPG_HOMEDIR"
          
          echo "some cmd"
          $GPG -d --batch --passphrase $CI_SAMPLE_VALUE file1.gpg
          
          echo "cleaning up"
          shred "$GPG_HOMEDIR"
          rm -rf "$GPG_HOMEDIR"
          echo "script done"
