name: iso_build
on:
  workflow_dispatch:
  schedule:
    - cron:  '30 6 1 * *'

jobs:
  release:
    runs-on: ubuntu-20.04  
    strategy:
      matrix:
        ##### EDIT ME #####      
        EDITION: [xfce]
        BRANCH: [stable]
        SCOPE: [minimal]
        ###################
    steps:
      - 
        name: Add SSH key
        env:
           SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p /home/runner/.ssh
          ssh-keyscan frs.sourceforge.net >> /home/runner/.ssh/known_hosts
          echo "${{ secrets.SF_PRIV_SSHKEY }}" > /home/runner/.ssh/github_actions
          chmod 600 /home/runner/.ssh/github_actions
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add /home/runner/.ssh/github_actions
      - 
        name: build
        env:
          EDITION: ${{ matrix.EDITION }}
          BRANCH: ${{ matrix.BRANCH }}
          SCOPE: ${{ matrix.SCOPE }}
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |                
          [ "$SCOPE" == "minimal" ] && unset SCOPE

          ##### EDIT ME #####
          
          KERNEL=linux510
          CODE_NAME="Ornara"
          VERSION=21.0
          PROJECT=manjarotest
          
          ###################
          
          mkdir -p $VERSION
          echo "file1" > $VERSION/file1
          echo "file2" > $VERSION/file2
          ls $VERSION
          
          rsync -vaP --stats -e ssh $VERSION ${{ secrets.SF_USER_NAME }}@frs.sourceforge.net:/home/frs/project/$PROJECT
