name: iso_build_osdn
on:
  workflow_dispatch:
#  schedule:
#    - cron:  '30 6 1 * *'

jobs:
  release:
    runs-on: ubuntu-20.04  
    strategy:
      matrix:
        ##### EDIT ME #####  
        EDITION: [xfce]
        BRANCH: [stable]
        SCOPE: [minimal]
        ###################
    steps:
      -
        name: Build ISO
        env:
          EDITION: ${{ matrix.EDITION }}
          BRANCH: ${{ matrix.BRANCH }}
          SCOPE: ${{ matrix.SCOPE }}
          ##### EDIT ME #####
          KERNEL: "linux510"
          CODE_NAME: "Ornara"
          VERSION: "test_upload"
          ###################
        run: |                
          [ "$SCOPE" == "minimal" ] && unset SCOPE
          
          echo "file1" > file1
          echo "file2" > file2
          echo "file3" > file3

          echo "FILE_PATH=file1" >> $GITHUB_ENV
          echo "FILE_SHA256=file2" >> $GITHUB_ENV
          echo "FILE_PKG=file3" >> $GITHUB_ENV
          echo "VERSION=test_upload" >> $GITHUB_ENV
      - 
        name: Add SSH key
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p /home/runner/.ssh
          ssh-keyscan frs.sourceforge.net >> /home/runner/.ssh/known_hosts
          ssh-keyscan storage.osdn.net >> /home/runner/.ssh/known_hosts
          echo "${{ secrets.SF_PRIV_SSHKEY }}" > /home/runner/.ssh/github_actions
          echo "${{ secrets.OSDN_PRIV_SSHKEY }}" >> /home/runner/.ssh/github_actions
          chmod 600 /home/runner/.ssh/github_actions
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add /home/runner/.ssh/github_actions       
      - 
        name: Upload to OSDN
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
          ##### EDIT ME #####
          PROJECT: "manjaro"
          ###################       
        run: |
          DATE=$(date +%y%m%d)
          rsync -vaP --stats -e ssh ${{ env.FILE_PATH }} ${{ env.FILE_PKG }} ${{ env.FILE_SHA256 }} ${{ secrets.OSDN_USER_NAME }}@storage.osdn.net:/storage/groups/m/ma/$PROJECT/${{ matrix.EDITION }}/${{ env.VERSION }}-$DATE
