name: 'Lock down repository'

on:
  pull_request:
    types: [ opened, reopened ]

jobs:
  lockdown:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/repo-lockdown@v2
        with:
          github-token: ${{ github.token }}
