name: 'Lock down repository'

on:
  pull_request:
    types: [ opened, reopened ]
  schedule:
      - cron: '0 * * * *'
jobs:
  lockdown:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/repo-lockdown@v2
        with:
          github-token: ${{ github.token }}
          close-pr: true
          lock-pr: true
