name: ping_cdn
on:
  workflow_dispatch:
#  schedule:
#    - cron:  '30 6 1 * *'

jobs:
  release:
    runs-on: ubuntu-20.04  
    steps:  
      - 
        name: Echo Git-Repo
        run: |
          echo "https://github.com/$GITHUB_REPOSITORY/releases/download/"    
      - 
        name: Ping CDN77  
        run: |
          ping download.manjaro.org -c 1
          sleep3
          ping download.manjaro.org -c 1
